### ISSUE TITLE
Attribute error line 367

### ISSUE THREAD

**Issue by kmarkley** [FlyingDiver/Indigo-Shims#20]
Since upgrading to v0.5.1 yesterday (from v0.4.0), I've been getting this error message on several of my devices:
```
   MQTT Shims Error                Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 115, in runConcurrentThread
  File "plugin.py", line 139, in processMessages
  File "plugin.py", line 367, in update
AttributeError: 'bool' object has no attribute 'lower'

   MQTT Shims Error                plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

Here's a sample MQTT payload for one of the problematic devices:
```
{"hostname": "pi-closet", "ip_address": "172.23.2.64", "cpu_serial": "0000000001b11915", "is_error": false, "error_msg": "", "timestamp": "2021-04-25 12:40:34", "connected": true}
```

And here's the device config:
<img width="471" alt="Screen Shot 2021-04-25 at 1 05 40 PM" src="https://user-images.githubusercontent.com/24628188/116004193-3d45ed80-a5c7-11eb-9661-c19c0902d311.png">

Thanks.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Shims/releases/tag/0.5.2

**Comment by kmarkley** [comment]
That got it.  Thanks.

**Comment by FlyingDiver** [comment]
Fixed in 0.5.2.
